# Generated by Django 6.0.2 on 2026-02-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(help_text='Employee ID', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField(max_length=100)),
                ('mtype', models.CharField(max_length=100)),
                ('mlength', models.FloatField()),
            ],
        ),
    ]
